on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

      
    # Set up node and install frontend dependencies
    - name: Set up Node.js (.nvmrc)
      uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: "npm"

    - name: Install dependencies
      run: npm ci

    - name: Generate list
      run: npm run import
    
    - name: Check for any changes and exit if none
      run: |
        if git diff --quiet HEAD^ HEAD; then
          echo "No changes detected. Exiting gracefully."
          exit 0
        else
          echo "Changes detected. Continuing with the workflow."
        fi
    
    - name: Run tests to make sure everything is coherent
      run: npm test

    - name: Set up git identity
      run: |
        git checkout main
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Increment the package.json version file
      run: npm version patch -f -m "🤖 Import updated chainlist rpcs, bump version to %s"
    
    - name: Push updated patch commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_NAME: ${{ github.repository }}
        USERNAME: ${{ github.repository_owner }}
      run: |
        git remote set-url --push origin https://$USERNAME:$GITHUB_TOKEN@github.com/$REPO_NAME
        git push